export const SHOW_WORDS_LIST = 'SHOW_WORDS_LIST';
export const SHOW_REGISTRATION_FORM = 'SHOW_REGISTRATION_FORM';
export const SHOW_LOGIN_FORM = 'SHOW_LOGIN_FORM';
export const SET_SOMETHING_SHOWN = 'SET_SOMETHING_SHOWN';